version: '3.3'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/web/staticfiles/
      
  web:
    build: ../app
    restart: always
    volumes:
      - static_volume:/usr/src/web/staticfiles/
    expose:
      - 8000
    env_file:
      - ./.env

volumes:
  static_volume:
